### ISSUE TITLE
Addition: New Data Element, Wireless Session Time

### ISSUE THREAD

**Issue by johnkerber** [IMLS/public-libraries-survey#13]
**New Definition:**  Report the total wireless session time and average wireless session time provided by the library wireless service annually.

Total wireless session time can be recorded by totaling all wireless session times for a year.  Average wireless session time can be derived by dividing the total wireless session time by the total wireless session counts (data element 652).  

**Rationale for Addition:**  To accurately compare how public wireless services are utilized by patrons across locations, knowing both the wireless counts and wireless time give a more accurate representation.

**Comment by mgolrick** [comment]
Given the difficulty of collecting the raw data - and I have been trying to do that in my state for about 5 years now - collection session length is not possible. I collect the stats for my agency, and I am not sure I can do that for my building, I can't ask others to collect something that I cannot.

**Comment by johnkerber** [comment]
Thank you for the comments Michael.

I agree that this was difficult to collect in the past, but new technology has made obtaining it possible.  For example, by storing each device in a database as it's seen, session time is now available across libraries of all sizes.

I'd be happy to send you my contact information, and we can discuss how this can be accomplished.

**Comment by mgolrick** [comment]
Let me remind you that many of us are dealing with small, rural libraries whose level of technical skills are limited. Even after asking for this data since 2012 (6 data collection cycles), I have libraries where staff still cannot provide me with the basic use data. The burden to collect this level of detail, as part of this survey, is such that I do not believe that it is possible.
