### ISSUE TITLE
Eliminate Data Element #460 - Print Serial Subscriptions

### ISSUE THREAD

**Issue by mgolrick** [IMLS/public-libraries-survey#17]
There was a time when this may have been a meaningful item, however, with the move to electronic/web information, this is not a meaningful item.

**Comment by kjcmetzger** [comment]
Anecdotal feedback from libraries here indicates no one uses this data and would not be upset if the data element were removed.

**Comment by ghost** [comment]
I agree with Michael that this data element is no longer relevant.

**Comment by jrnelson1201** [comment]
Do we currently count anywhere in circulation data? Would any other definitions need to be updated/clarified if the change takes place?

**Comment by mgolrick** [comment]
This is a collection count issue, not circulation. If items circulate, it would be in that group.

**Comment by jrnelson1201** [comment]
Right, but is there a corresponding circulating count? Or is it included in the circulating definition? Or am I missing something obvious?

Jennifer R. Nelson
Director, State Library Services and Charter Center
651-582-8791 |  jennifer.r.nelson@state.mn.us<mailto:jennifer.r.nelson@state.mn.us>

Minnesota Department of Education
1500 Highway 36 West, Roseville, MN 55113
education.mn.gov<https://education.mn.gov/>

[Minnesota Department of Education]

**Comment by mgolrick** [comment]
To the best of my knowledge, there is no corresponding circulation count. (Unless states include it as a state-level question, which I do not.)

**Comment by ghost** [comment]
I don't know about that. I would report is on 553 Physical Item
Circulation. According to the definition: "The total annual circulation of
all physical library materials of all types, including renewals. Note:
Count all physical materials in all formats that are charged out for use
outside the library."

Print periodicals would definitely count as "physical materials in all
formats." I have always included use of print serials in 553. But this is
different from element 460. The circulation issue is done by issue rather
than by subscription. Maybe I'm not seeing this the right way, but these
two 460 and 553 are unrelated data elements.

Scott

*Scott Dermont* Library Consultant
*State Library of Iowa* | Des Moines Office
515.281.7573 | scott.dermont@iowa.gov <First.Last@iowa.gov>
1112 E. Grand Avenue | Des Moines, IA 50319
www.StateLibraryofIowa.org <http://www.statelibraryofiowa.org/>

**Comment by timrohe** [comment]
The only thing I can see that might complicate this issue is that some libraries circulate serials "outside the library," as required by 553 Physical Item Circulation, and some don't.  For those that do, I can kind of understand the desire to have a corresponding number in the collection count, should a library want to measure total physical holdings against 553.  That would be the only argument I can see for keeping 460 Current Print Serial Subscriptions, even though total physical holdings isn't a data element measured by the PLS.  However, 460 isn't really an accurate reflection of the collection count for serials anyway, since it only counts how many serials a library subscribes to.  When you consider that, for the libraries that do circulate serials, it is oftentimes just back issues, that makes 460 an even more imperfect data element to act as a corresponding collection count for any serial circulation numbers included in 553.  Long story short, I'd be fine getting rid of 460, but I also don't see the harm of leaving it.  The burden of collection isn't so great as to make it a high priority for removal.

**Comment by mgolrick** [comment]
Actually, in theory, everything bar coded (each back issue of a magazine) could be included in 450. That is separate from the number of subscriptions which is what is asked for ibn 460.

**Comment by timrohe** [comment]
Michael, thank you for pointing that out; honestly, I'm a little embarrased that didn't occur to me.
