### ISSUE TITLE
652 - Wireless Sessions Reporting Method

### ISSUE THREAD

**Issue by ThomasIvie** [IMLS/public-libraries-survey#22]
**Name:** Thomas Ivie
**State:** Wyoming

**Definition:** Reporting method used for element 652, Wireless Sessions

**Addition of Note** (as included with 501, 502, 651 and 653): If the data element is collected as a weekly figure, multiply that figure by 52 to annualize it. Libraries unable to collect a count of their wireless sessions should report "-1" (missing). Libraries that do not offer wireless connections should report "-3" (not applicable).

**Instrumentation**: A fixed-choice question directly after entry of data element 652, which would read:

For the previous data element (652, Wireless Sessions), which of the following reporting methods did you use?
-Actual count
-Annual estimate based on a "typical week."

**Rationale:** Information about the reporting and method will provide consistency, analytical flexibility and precision.

**Comment by yanademireva** [comment]
I would be curious to know what actions would be taken given one choice or another? If they are performing an actual count rather than a sample (or vice versa), how would that affect data analysis and any decisions based on that analysis? There are several elements for which I would love to know the method of collection, so I'm just trying to get a better picture of how having that information for this particular element will be helpful. 

Yana
Yana Demireva
Research & Evaluation Coordinator
Maryland State Library
