### ISSUE TITLE
Delete LIBID from the File Specs

### ISSUE THREAD

**Issue by mgolrick** [IMLS/public-libraries-survey#26]
The instructions say that this is "State assigned identification number MUST BE UNIQUE"

It is likely not used by most of us given that there are already FSCSKEY and FSCSSEQ numbers to uniquely identify libraries. It is just one more confusing field.

**Comment by enielsen-air** [comment]
This change would require re-developing the architecture of how Structure Status changes work in the PLS Web Portal.  LIBID is the default record identifier until the FSCSKEY/SEQ are assigned, which doesn't happen until the SDC passes the Match Report.  As a result, LIBID of the AE is referenced in the PARENTID field on outlet records when outlets are added or merged (STATSTRU 02, 05, 13, or 22). This cannot be changed to use FSCSKEY instead because when the AE is also being added, that value is not known when the Outlet file is imported. I won't argue that these ID fields are confusing, but you can always perform Structure Status changes via the Web Portal user interface if you want to avoid them.

**Comment by vdgreenwood** [comment]
@mgolrick, I use this field a great deal!  Removing it would add significantly to my time, matching up my 550-or so AE's.

I'm relieved to see @enielsen-air 's comment that it is somewhat integral to the portal!

Valicia Greenwood
Library Data Coordinator
Texas State Library and Archives Commission

**Comment by Chilcoat** [comment]
I hate the LIBIDs, but sounds like they're useful in several ways.

**Comment by rossfuqua** [comment]
We're trying hard to get our LIBIDs to match our AEs' FSCSIDs in Oregon, but with so many births, deaths, marriages, and divorces here all the time, our LIBIDs come in real handy.
