### ISSUE TITLE
Please comment: FY20 COVID-19 Questions to Repeat in FY21

### ISSUE THREAD

**Issue by lfrehill** [IMLS/public-libraries-survey#31]
There were 13 questions added to the Administrative Entity level and 2 to the Outlet level Public Libraries Survey for FY 20. Consider how libraries are continuing to operate, changes over the past six months, and what might be changing in the next 12 months. 

- Which of these 15 items should be retained for the FY 21 PLS? 

- Are there edits necessary in items that should be retained? 

- Should any of these items be dropped in FY 21? 

The attachment includes the data element numbers, variable names, and definitions. 

[Questions FROM OMB package for Github 2020-08-28.docx](https://github.com/IMLS/public-libraries-survey/files/5144246/Questions.FROM.OMB.package.for.Github.2020-08-28.docx)

**Comment by ghost** [comment]
Since these questions are not year specific, we'd want to reword them to indicate that we are talking about FY21, since they already answered for FY20.

I think we can take out all the "before COVID-19" questions since the libraries should have already answered that question in the FY20 PLS. That includes 513 and 519.

I'm not convinced that 521 or 522 are useful so I would suggest removing them for next year.

I don't think we need edits for these Yes/No questions. We shouldn't compare to PY as their answer could be different from year to year.

**Comment by mgolrick** [comment]
Remember, some of us have not collected the 2020 data yet. Group 2 just completed (or is about to complete) submitting 2019 data. (For my state, that's data covering January - December 2019.) I am just now thinking about 2020.

**Comment by ghost** [comment]
I haven't started my FY20 data collection yet, but I already have
opinions...

Scott

*Scott Dermont* Library Consultant
*State Library of Iowa* | Des Moines Office
515.281.7573 | scott.dermont@iowa.gov <First.Last@iowa.gov>
1112 E. Grand Avenue | Des Moines, IA 50319
www.StateLibraryofIowa.org <http://www.statelibraryofiowa.org/>

**Comment by mgolrick** [comment]
I just re-read the descriptions of #715 & #716 and went back to the current definition of #714. Is it true that the sum of 714 + 715 + 716 should be equal to 52? And if that is so, why is there the limitation that 716 cannot be greater than 714. Depending on what Phase of reopening a state is in, it could well be a larger number.

Group 2 example (Calendar Year data): If an outlet closed on March 15 because of COVID, and then reopened with limited services on June 5, and if they do not return to full service by the end of the year. Then 714 could be 13, 715 could be 12, and 716 could be 27.

Or are you trying to say that 714 indicates any level of being open to the public? If so, then the current definition of 714 should be clearly re-written to indicate that explicitly.

714 is **Number of Weeks an Outlet is Open (actual weeks)** (WKS_OPEN)
715 is **Number   of Weeks an Outlet Closed Due to COVID-19** (C19WKSCL)
716 is **Number   of Weeks an Outlet Had Limited Occupancy Due to COVID-19** (C19WKSLO)

**Comment by enielsen-air** [comment]
@mgolrick We intentionally did not change the definition of 714 (WKS_OPEN) for FY 2020.  We intended 716 (C19WKSLO) to be a subset of 714.  But I recognize that the definition of 714 includes this caveat: "The count should be based on the number of weeks that a library outlet was open for half or more of its scheduled service hours." If the phrase "scheduled service hours" is interpreted as pre-COVID service hours (and if libraries are closely following the definition), it is possible that they would count weeks in 716 that are not counted in 714. Otherwise, if "scheduled service hours" means planned according to COVID-related restrictions, they 716 should be a subset of 714.

Either way, I agree that the definition could use refining around that phrase.  And it would be best if it was not COVID-specific, because I can imagine other scenarios where the meaning of "scheduled service hours" would be unclear.

**Comment by timrohe** [comment]
@enielsen-air Just to make sure I understand this correctly, there are, effectively, six categories of a library being open or closed that people need to keep straight in their head:
1. Number of weeks an outlet is open "for half or more of its scheduled service hours."
2. Number of weeks an outlet is open for less than half of its scheduled hours due to a non-COVID-19 related event.
3. Number of weeks an outlet is open "for half or more of its scheduled service hours" with limited occupancy due to COVID-19.
4. Number of weeks an outlet is open for less than half of its scheduled service hours with limited occupancy due to COVID-19.
5. Number of weeks an outlet was closed due to COVID-19.
6. Number of weeks an outlet was closed due to a non-COVID-19 related event.

I _think_ that's it.  So, then, 714 equals 1 and 3 and 716 equals 3 and 4, while 715 is just 5.  2 and 6 are lumped together, in the sense that they don't get counted anywhere, even though they are qualitatively different.

Not only is this is pretty confusing, it precludes 716 from being a subset of 714.  This is partly because @mgolrick is correct that 716 could be greater than 714.  The problem with this is that, although the definition says that 716 simply _should not_ be greater than 714, there is an edit check on 716 that gets triggered if it is, in fact, greater than 714.  In practice, this means that 716 _must not_ be greater than 714, even though this is entirely possible.  I know that I can turn off that edit check at the local level, but it will just get triggered when I submit my data to AIR, correct?

I'm struggling with a solution to this dilemma.  It's too late to officially take the edit check in question off of 716, since some libraries have actually started, and possibly finished, their FY2020 data collection.  Likewise, it's too late to officially make 716 a subset of 714 by adding in the language of being open with limited occupancy for at least half or more of a library's scheduled service hours.  The latter seems like it makes the most sense, though, since we don't count hours where the library is open less than half its normal hours due to a non-COVID-19 event, so why count them just because it is due to COVID-19?  I don't see any other workable solution that would allow for the reality that 716 can be greater than 714, other than to ignore the official definitions, which is less than ideal.

**Comment by enielsen-air** [comment]
I want to reiterate that the potential problems with counting outlet hours are contingent on the definition of "scheduled service hours" in data element 714.  Who determines the schedule?  When is it established?  I expect some libraries could rationalize that they reduced their scheduled service hours in response to the pandemic, so therefore all of the weeks their buildings were open at all count toward 714.

Yes, 716 is intended to capture the number of weeks with limited occupancy policies, regardless of comparison to "scheduled service hours." And I can now see that defining 716 to be less than 714 may have been short-sighted.

I also agree that this will be difficult to resolve.  However, I expect it would be rare for libraries in Group 1 states that have finished their data collection ran into a problem with 716 being greater than 714, given the timing of their fiscal years and the pandemic shutdowns.  But it could be an issue for Group 2 states, again, depending on the interpretation of the phrase "scheduled service hours."

Lastly, I think we all knew that these COVID items would be imperfect for FY 2020 given how quickly we had to develop and implement them. Which is why it is good to start this discussion now for FY 2021. Thank you all for your input!

**Comment by kjcmetzger** [comment]
There has been a lot of confusion about this. I've advised libraries not to count a week in more than one place, rather than get into the caveats of the definition. Even then, libraries are still having to correct their initial responses. The definitions could definitely use some revision to make them clearer. I think 714, 715, and 716 should be mutually exclusive.

**Comment by mihalc** [comment]
We are running into confusion on 714, 715 and 716 as well, so some clarification would be helpful. 
We are currently collecting for 2020 and have libraries that are reporting for Jan. 2019 - Dec. 2019. These libraries will be reporting for Jan. 2020 - Dec. 2020 next year and will need all of the data elements for what happened before and after COVID. I would like to see these questions retained for FY21, including questions about before COVID as some will still be reporting some pre-COVID months next year.
Cory Mihalik
Missouri.

**Comment by vdgreenwood** [comment]
The current additions refer to the COVID-19 pandemic as though it were a done deal.  Not in Texas!  I still have libraries that are closed, have furloughed staff, and/or are open for limited services.  We do not have a sense when they will be open because stay-at-home orders are continuing through December, at least in some places. 

The questions should be continued at least for the 2021 collection, and reviewed after that point.

Valicia Greenwood
Library Data Coordinator
Library Development and Networking Diviision
Texas State Library and Archives Commission

**Comment by jrnelson1201** [comment]
I would continue to ask in 2021

**Comment by yanademireva** [comment]
I do think we should continue to ask some of the questions in FY21, especially around closures, hours, and staff. I'm not so sure about service-related ones, however. At what point are libraries thinking about the changes in their services as a reaction to/result of the pandemic, versus just something that they now do? For example, libraries that initially increased their e-book collections or added e-cards may have done so in order to meet a pandemic-related need. However, now that they have these new services, are they continuing to think about them as pandemic-related? Will they be able to make the distinction between adding these services in FY20 versus continuing them in FY21? I know these are simple Y/N questions, but I do think they will become increasingly difficult for libraries to answer. We're asking for concrete point-in-time answers (Yes, we added e-books/No we did not provide virtual reference) for an ongoing situation that doesn't have a clear beginning/end, and things change back and forth constantly. **TL;DR** - keep ones on closures/hours/staffing and eliminate service-related ones.

**Comment by KathleenSullivan** [comment]
I agree with @yanademireva. After 2020, it's much more difficult to say what changes are a reaction to the pandemic and which are evolution prompted by the pandemic. ...These COVID-specific questions made perfect sense for this year, but from FY21 forward, what about having just a few questions that capture disruptions in services or facility access for whatever unpredictable reason. (In WA, for example, we have questions about branch closures for natural disaster/construction/budget but also an "other" category.)
