### ISSUE TITLE
Addition - Program Sessions/Attendance by Target Age

### ISSUE THREAD

**Issue by enielsen-air** [IMLS/public-libraries-survey#36]
**SUBMITTER:**
Evan Nielsen (AIR) on behalf of IMLS and the LSWG PLS Methods Ad Hoc Subcommittee

**NEW DATA ELEMENTS:** 
- Number of Program Sessions Targeted at Children Ages 0-5 (data element 601)
  - _With new data element 602, replaces current data element 601 (KIDPRO)_
- Number of Program Sessions Targeted at Children Ages 6-11 (data element 602)
  - _With new data element 601, replaces current data element 601 (KIDPRO)_
- Number of Program Sessions Targeted at Young Adults Ages 12 to 18 (data element 603; _revised from current data element 602 YAPRO_)
- Number of Program Sessions Targeted at Adults Age 19 or Older (data element 604)
- Number of General Interest Program Sessions (data element 605)
- Attendance/Views for Programs Targeted at Children Ages 0-5 (data element 611) 
  - _With new data element 612, replaces current data element 604 (KIDATTEN)_
- Attendance/Views for Programs Targeted at Children Ages 6-11 (data element 612)
  - _With new data element 611, replaces current data element 604 (KIDATTEN)_
- Attendance/Views for Programs Targeted at Young Adults Ages 12-18 (data element 613; _revised from current data element 605 YAATTEN_)
- Attendance/Views for Programs Targeted at Adults Age 19 or Older (data element 614)
- Attendance/Views for General Interest Programs (data element 615)

**RATIONALE:**
This proposal is one of three interrelated proposals for changes and additions to the library programs data elements. The SDCs and the LSWG have indicated a need to gather additional data about library programming since it is such an expanding and changing library service. Particularly, data users have noted that the existing program data elements for children and young adults do not reflect an exhaustive list of age categories, and thus do not sum to the totals. A series of data elements were developed based on a review of existing state library surveys and the IMLS State Program Report system. The potential data elements were vetted in one-hour interviews with nine respondents from public libraries of various sizes in seven different states. The interviews informed the work of an ad hoc subcommittee of LSWG members and staff from IMLS and AIR to refine the revised data element definitions proposed here. 

The ten data elements presented in this proposal represent five exhaustive and mutually exclusive target age categories that would sum to the Total data elements for programs and attendance. Thus, they should be approved or rejected as a set.

**PROPOSED DEFINITIONS:**
See attached file (link below) for the proposed definitions.
[PLS Program Items_Target Ages.docx](https://github.com/IMLS/public-libraries-survey/files/5165164/PLS.Program.Items_Target.Ages.docx)

**Comment by timrohe** [comment]
I was opposed to this when we voted it down at the annual meeting and I am still mostly opposed to this.  I personally think breaking up children's programs into 0-5 and 6-11 is too many categories.  I also prefer continuing to use the terms Children's and YA, and then I'm fine with subsequently adding Adult and General Interest, rather than citing specific age ranges.  The age ranges can go in the definition of each category as guidance, but I think citing them in the name of the data element is too specific.  There is often some bleed over between categories, particularly between children's and YA, and this proposal is a little too rigid for that, whereas I can usually get the director to pin down whether the spirit of the program is children's or YA, if that makes any sense.

**Comment by jrnelson1201** [comment]
I see value in finer breakdown of age categories that is proposed. Early literacy is a key component of library value and the more ways we can talk about it with data, the better. Likewise for school age and teen.

**Comment by timrohe** [comment]
One other factor that I was recently reminded of is that such a major change would cause a hard break with the past, meaning that you would basically restart the clock on the ability to make any comparisons to historical data.  Just something to consider.

**Comment by timrohe** [comment]
@jrnelson1201 Would you say that it's fair to assume that all programs for 0-5 year olds are early literacy programs?  The reason I ask is because 0-5 is an age range, while "early literacy" is a type of program.  I suspect they're not, so, if not all programs for 0-5 year olds are early literacy programs, you're still not getting the data you want.  However, you could add 'number of early literacy programs' as a local question to accomplish that goal.  If all programs for 0-5 year olds are early literacy programs, then why not just call the category 'Early Literacy Programs,' as that seems more intuitive to me.
