### ISSUE TITLE
Revision: 458 Total Electronic Collections (ELECCOLL)

### ISSUE THREAD

**Issue by KathleenSullivan** [IMLS/public-libraries-survey#43]
**Your names**: Kathleen Sullivan (WA), on behalf of the SDC Electronic Materials FAQ Working Group (Yana Demireva (MD), Chris Guerra (AZ), Joseph Hamlin (MI), Kelly Metzger (RI), Kathleen Sullivan (WA))

**Number of data element you seek to change:** 458 Total Electronic Collections (ELECCOLL)

**Proposed change**: Include all electronic content under this element, counting each service (e.g., OverDrive, Kanopy, etc.) as one unit. Distinct services offered by the same vendor may be counted separately (e.g., EBSCO Public Library eBooks, EBSCO databases).

This change will apply to related data elements 456 (Local/Other cooperative Agreements) and 457 (State).

**Rationale for change**: Counting each product as a single unit provides a value that is reliable in its accuracy as well as aggregable at the national level. It does this by removing the need to force a one-to-one correlation between metrics which have no commonality, such as Tutor.com sessions with Gale retrievals. More importantly, it removes the need to make annual determinations of whether a product’s offerings should be considered a “collection” or “material” – a determination that already lacks merit due to the existing mash-up of offerings a single product can offer.

**Comment by mihalc** [comment]
Since there were a lot of proposed changes, I'm going to comment on most of the changes to 451-458 here. I understand that the gathering of e-collection numbers can be inconsistent by vendor and database. However, I don't exactly understand what the "one product is one unit" approach gets us. I understand it simplifies the process, but I think we're going to be missing out on a lot of data with this simplification. In Missouri our libraries differ pretty dramatically in collection size even within a specific product. So, while a small rural library may have several hundred Overdrive titles, our larger systems will have several hundred thousand Overdrive titles. A "one" count for Overdrive for both of these libraries shows some sort of equivalency that I don't think is correct. 451-458 gave some sort of value, that while flawed, still helped give an idea of the amount of loan-able e-content a library had to offer. Reporting of a collection of 250,000 e-books gives me a relative idea of the amount of content available, while a listing of 3 services really doesn't tell me much. Either way, I guess I will try to keep gathering this at the state level.

**Comment by KathleenSullivan** [comment]
@mihalc. Our group figured that the larger "collections" would still be reflected in expenditures for electronic content, as well as usage (in the case of OverDrive, number of materials loaned out). So the large system with hundreds of thousands of Overdrive titles would have larger expenditures, and higher usage statistics, right? We'd still be able to see that, but we wouldn't have to keep explaining why libraries shouldn't count the entire Kanopy catalog as part of their collection.
