### ISSUE TITLE
Revision (with options to add new sub-elements): 552 Use of Electronic Material (ELMATCIR)

### ISSUE THREAD

**Issue by KathleenSullivan** [IMLS/public-libraries-survey#44]
**Your names**: Kathleen Sullivan (WA), on behalf of the SDC Electronic Materials FAQ Working Group (Yana Demireva (MD), Chris Guerra (AZ), Joseph Hamlin (MI), Kelly Metzger (RI), Kathleen Sullivan (WA))

**Number of data element you seek to change**: 552 Use of Electronic Material (ELMATCIR)

**Proposed change**: Count as one use the circulation of any electronic content with a loan period without making a distinction as to whether it comes from “collections” or “materials.” 

This change can also include **_additional sub-elements_** that separate usage based on the specific type of content, such as e-books (552a), downloadable audiobooks (552b), downloadable videos (552c), and downloadable “other” content (e.g., music, scores, maps) (552d). 

**Rationale for change**: The proposed change simplifies the process of determining what to count for circulation by removing the restriction based on product criteria, such as mode of payment or method of access.

**Comment by jrnelson1201** [comment]
This seems quite sensible.

**Comment by ghost** [comment]
To clarify, we are removing the downloadable collection counts but retaining and refining the downloadable use counts? I agree that counting downloadable collections has become a real headache with all of the different service models on the market right now and I'm not sure how valuable that count is. But use counts are pretty straight forward for me, so I would be in favor of keeping them. I'm not sure about the wording in the rational as far as product criteria and mode of payment. Can you clear that part up? It might help if the proposed change include the actual text of the revised data element.

**Comment by timrohe** [comment]
@sdermont I was wondering about the mode of payment issue myself, so thank you for raising it.  I also agree that the actual text of the revision would help.  *checks to make sure I added the definition in all of my proposals*  I think the actual text of any new or revised data elements should be mandatory for submission.

**Comment by az-cguerra** [comment]
@sdermont  What we are saying is that no other factors should matter regarding whether or not to count the circulation of digital content. That includes mode of payment and product criteria. If it has a circulation period, count it by type (e-book, video, etc.). This is in conjunction with another of our proposals to remove the distinction between databases and materials. These all-encompassing circulation values along with our proposal to count the number of times an electronic product is accessed would be how we track overall usage.

As an aside, I've read in another post the position that access to an electronic product does not equal usage, however, I feel like that distinction depends on whether you're looking at the product or the product's individual content. To me, if you're looking at the product as a whole, accessing it is usage.

**Comment by ghost** [comment]
@az-cguerra if that is the case, then I think you need to delete the existing data element and create new ones. The proposed definition would make it useless for comparison to previous years as these are two totally separate statistics. Number of sessions and number of uses may both be useful data, but they are not the same data. 

If we refer back to that Z39-7 protocol on electronic use, it defines both sessions and uses as separate data elements. I believe that the protocol recommends counting them both - but separately rather than together. Again, I only bring that up because we designed the original electronic use definitions to be consistent with that protocol. At the time we chose to count uses rather than the other elements (I think there are four), because it was the closest analog to the existing circulation data elements. The idea then was to give libraries several different use totals (physical, electronic, all) to use when looking at their use statistics. 

At least that is my recollection of how it went. If there was anyone else on that original committee that can remember it better than that please clarify if you can.

**Comment by vgetahun** [comment]
Hard to know where to add my comments about the many-headed beast of electronic resources, especially as they don’t add up to a coherent Yes or No to any of the proposals.
Is it ever the case that one would NOT count usage of electronic content with a loan period under 552? Just from looking at the definitions of 552 and 554, it seems the distinction between the two measures of usage already hinges on whether or not there is a loan period. So I don’t know if we need to modify the definition of 552. Even if we accept the proposed changes to the way we count electronic holdings – eliminating counts of individual content units and instead counting at the level of a “product” – that wouldn’t change where we record usage of those products.
And regarding that proposed change to 458: It’s tempting to be able to let go of that annual determination of collection versus material. But because people are people, I imagine there will still be differing interpretations about what constitutes a product or a “distinct service.” If this goes forward, I think we would need to round out the criteria that define a product.
I agree with Scott Dermont’s comment here that, if we switch to counting logins, we would treat that as a new element, not continuous with 554. We’re essentially saying that it’s impossible [for now] to come up with one reliable number for all the ways that someone engages with electronic content with no loan period. Instead, we will use one number that measures how many times someone, as @az-cquerra puts it, “goes out of their way to use the product.”

**Comment by KathleenSullivan** [comment]
@vgetahun. Thanks for this question ("Is there a case where one would NOT count usage of electronic content with a loan period under 552?") Usually, no ...except sometimes. If states follow the attached flow chart, then they'll nearly always count services with loan periods under "Electronic Materials' and count the number of materials loaned. (There's still confusion over what to count in the "collection," which hinges on the payment model, but that's another of the many-headed revisions.) ...However! there are discrepancies among states about whether certain services are "Materials" (in which case the loaned items get counted) or "Collections" (or databases, in which you count retrievals, or try to). On Hoopla, for example, states were about evenly split in directing libraries to count it as a material or a collection/database. If a service is categorized as a database, but "loans" content out for a temporary period, those loans wouldn't get counted under 552. ...Tired yet? This is why our group's proposals are a many-headed-beast, because the use
 counting is currently knotted up with the attempt to distinguish between databases/collections and materials. 

[ElectronicContentFlowChart.xlsx](https://github.com/IMLS/public-libraries-survey/files/5228855/ElectronicContentFlowChart.xlsx)
