### ISSUE TITLE
Revision: 554 Successful Retrieval of Electronic Information (ELINFO)

### ISSUE THREAD

**Issue by KathleenSullivan** [IMLS/public-libraries-survey#45]
**Your names**: Kathleen Sullivan (WA), on behalf of the SDC Electronic Materials FAQ Working Group (Yana Demireva (MD), Chris Guerra (AZ), Joseph Hamlin (MI), Kelly Metzger (RI), Kathleen Sullivan (WA))

**Number of data element you seek to change**: 554 Successful Retrieval of Electronic Information (ELINFO)

**Proposed change**: For electronic services that offer content with no loan periods, count as one use a single access of the electronic service by an authenticated user (_e.g_., a patron logs in to Freegal).

**Rationale for change**: This eliminates the current definition’s emphasis on patrons’ sufficiently viewing/examining/downloading “full” content, which is confusing or impossible to track among dozens of products, and results in unreliable and inconsistent counts.

**Comment by ghost** [comment]
I just want to be clear here. Does this mean that we are counting logins rather than use? This could give a drastically difference count (much lower I would think) than what we have now. In my mind a login is not a retrieval.

**Comment by enielsen-air** [comment]
While I'm sure someone will find fault with this dichotomy, I think the basic question is whether we want to count the number of times someone goes searching for information or the number of search results someone accessed.  The current definition measures the latter; the new definition measures the former.  But @sdermont has a point that the name of the data element may need to be revised along with the definition, if this moves forward.

**Comment by KathleenSullivan** [comment]
@sdermont Yes, it means counting logins. I appreciate the fact that this will likely lower overall counts. I still think a login count will be more valid than the current e-retrievals measure, which attempts to assess whether the patron actually retrieved content or fully "used" the service. Apart from anything else we might say about that (do we only count a checkout if the patron actually reads the book?), it's effectively impossible for libraries to track what to count across multiple products, and then sometimes impossible to wring the count out of the product (even when the library knows exactly what it wants).

**Comment by timrohe** [comment]
@KathleenSullivan In response to your question, "do we only count a checkout if the patron actually reads the book?" no, we don't.  But I kind of feel like only counting logins is like trying to approximate physical circulation by only counting visits to the  library.

**Comment by ghost** [comment]
I think @timrohe makes a good point here. I can see where some logins or sessions would be used as a use count. Some resources like language learning software count sessions as use as they don't really have "downloads." I usually count those when it makes sense. But a database product, like Gale or EbscoHost, uses a download or record view as a use. Those two products don't have a "loan period" so in the new proposal you would only be counting logins for these resources. In those cases you would definitely be counting two very different things - download versus login. 

I also want to point out that when we originally created this data element we were trying to be consistent with the  use definitions found in the Z39-7 protocol. If I recall, we did this to try to be consistent with how academic libraries and other institutions count the use of electronic resources. Maybe that doesn't matter anymore, but at the time it made sense to be consistent with existing standards.

**Comment by timrohe** [comment]
I have two primary concerns with this.  I'm going to use EBSCO as the exemplar because it's notorious on both of these.  First, counting logins is essentially counting sessions; every time you login, you start a new session.  However, EBSCO frequently checks to make sure you're not idle, so it pings the system for authentication.  Two things can happen here.  If you're using a physical login, i.e. typing in a username and password, it can log you out and then you have to type in your username and password again.  This scenario isn't too big of a deal.  If the patron walked away, they don't log back in.  If they're still using it, they log back in, and your numbers aren't too inflated.  

The real issue comes when you have the account linked to your IP address, which is the case for in-house use of EBSCO at many libraries, such as here at the NH State Library.  EBSCO pings the system for authentication, the system sends the info. (your "login" credentials), and EBSCO starts a new session.  I believe EBSCO does this rather frequently, possibly even every 30 mins.  You could potentially have a "login" every 30 mins.  Also, EBSCO allows you to search across multiple databases.  Each one of those is asking for authentication, so each search counts as a "login" with your credentials.  I know I frequently just select all databases because I'm lazy, so that's a login for all 22 databases we have access to here at the library.

Second, several libraries have a federated search system on their OPAC that searches some databases, like EBSCO, for relevant results.  Every time it searches EBSCO, it asks for authentication, hence a new "login."  You're getting a login every time someone searches the catalog.

The general wisdom is that that stats would go down if we switch from "usage" to logins.  I fear it would be the opposite.  I fear this could be another overly inflated number that essentially tells you nothing.  For example, I checked my local public library.  For FY2019, their usage stats are 2,252, using the current definition.  The number of logins/sessions over the same period is 4,472.  I was told that they recently "fixed" their OPAC so it does not automatically search EBSCO and that, prior to the fix, their EBSCO sessions were in the millions.

My colleague that I worked with on this said that the PLS used to count database sessions but, for all of the reasons above, stopped doing so maybe back around 2015.  Does this ring a bell for anyone who's been around for a while?

**Comment by ghost** [comment]
@timrohe - we never counted database sessions (at least since 2008). The database count on the PLS was for number of subscription databases. Usage wasn't tracked until the existing elements were created. With that said, it could be that your state survey included a sessions count. I think there were several states counting a variety of electronic stats before we incorporated the electronic use counts onto the PLS.

**Comment by NormaFNev** [comment]
I freely admit that I'm having trouble wrapping my head around all of the interrelated proposals and may be missing the finer points. However, as I understand it, I agree with Tim and Scott. This seems to be me to be conflating different things - services with content such as Freegal or Kanopy vs databases such as Ebsco (as Scott stated above). I spent quite a bit of time this week getting usage stats for our statewide databases, and I don't see that counting log-ins for Ebsco, Learning Express, etc, is an accurate reflection of usage.

**Comment by az-cguerra** [comment]
@NormaFNev  You are correct that it conflates those types of services together, because the intent of all the changes is to remove the need to make a distinction between materials and databases (electronic content) so that we can measure something a bit more... well, measurable, without going to extraordinarily painful lengths. By doing it at the point of entry (access) instead of at the myriad points of engagement we start aggregating numbers that are the same, even if the exact numbers are not 100% evenly counted (I'll address Tim's point on that in a minute). One of the reasons for this is that it has become too hard to separate the available products definitively into one category or the other, and this problem will only be exasperated over time. The other major difficulty is in trying to figure out what counts as a "retrieval" for a database. I won't go further into the "retrieval" issue since that is discussed in a different proposal, but suffice it to say that I believe in its current form it aggregates values that have little to do with each other ("apples and cars" as opposed to just "apples and oranges").

The reason we went with electronic circulation and access of electronic products is two-fold: (1) on the surface, they're conceptually easy to understand (Did it circulate/download? Did they login?); and (2) they're the most likely to be aggregable (well, as compared to anything else) that we can collect. Personally, I can't think of any other metric we could track that is somewhat meaningful to these electronic content packages libraries are purchasing. With this and all the other proposals we've put forth, what we're saying is "here are the number of electronic products libraries are paying for;" "here is the number of times people are going out of their way to use the product;" and "here is the number of times people are circulating/downloading individual e-books, audiobooks, music, and videos." To respond to Tim's point regarding the inflated value, yes, I agree that it can and will happen to varying degrees. This is much like it is now with what we currently collect, and also in the same vein of so many other stats (e.g. Wi-Fi usage). As such, I'm certainly on board with only ever collecting circulation, however, I feel like the push-back on that would be even greater. It seems people really want a national value of some kind to reflect electronic usage for trend and comparison purposes. The problem is that the sheer complexity of electronic content availability and usage does not lend itself well to generating all-encompassing values.
