### ISSUE TITLE
Addition - Partnerships by Organization Type

### ISSUE THREAD

**Issue by enielsen-air** [IMLS/public-libraries-survey#47]
**SUBMITTER:**
Evan Nielsen (AIR) on behalf of IMLS and the LSWG PLS Methods Ad Hoc Subcommittee

**NEW DATA ELEMENTS:** 
•	Partnership with State Government Agency (data element 530)
•	Partnership with Local Government Agency (data element 531)
•	Partnership with K-12 School or District (data element 532)
•	Partnership with Institution of Higher Education (data element 533)
•	Partnership with Museum or Historical Society (data element 534)
•	Partnership with Non-Profit Organization (data element 535)
•	Partnership with For-Profit Organization (data element 536)
•	Partnership with Tribal Organization (data element 537)
•	Partnership with Other Organization (data element 538)

**RATIONALE:**
This proposal adds nine data elements that are yes/no indicators of formal partnerships between a library and various types of organizations. The LSWG has identified a need to capture the ways that public libraries work collaboratively with other organizations and agencies, particularly at the local level, to provide services to their communities. These proposed data elements would allow IMLS at starting point for documenting these partnerships from the entire universe of public libraries, beyond what is currently captured in the State Program Report for LSTA grants.

These proposed data elements are currently being vetted in one-hour interviews with ten respondents from public libraries of various sizes in seven different states. These interviews, along with feedback from SDCs via this forum, will inform the work of an ad hoc subcommittee of LSWG members and staff from IMLS and AIR to refine the proposed data element definitions and conduct another round of interviews in the fall. 

The nine data elements presented in this proposal should be approved or rejected as a set.

**PROPOSED DEFINITIONS:**
See attached file (link below) for the proposed definitions.
[PLS Partnership Data Elements for FY22.docx](https://github.com/IMLS/public-libraries-survey/files/6928252/PLS.Partnership.Data.Elements.for.FY22.docx)

**Comment by mariabernier10601** [comment]
Some of my libraries have difficulty distinguishing partners from paid contractors. Please add clarifying language about partnerships being reciprocal, e.g. both parties contribute and both parties benefit, quid pro quo, two-way street, etc. Also, clarify that a "formal" partnership is one that is described and agreed upon in writing, possibly in an MOU, MOA, letter of agreement, or something similar. Under the current definition and descriptions, many of my libraries will argue that because they post program flyers for neighboring nonprofits on their bulletin boards, all of those nonprofits can be counted as partners. Hence the need to clarify.

**Comment by dennisonmich** [comment]
A good opportunity to have consistency since IMLS already has a published definition for "partner" (yes, I realize this element proposal is for "partnership" and not "partner"). From [https://www.imls.gov/sites/default/files/imlsstateprogramreportingrequirements.pdf](https://www.imls.gov/sites/default/files/imlsstateprogramreportingrequirements.pdf) (IMLS LSTA State Program Reporting Requirements)
"Partner: A cooperating institution, designated through a formal agreement that contributes material resources (i.e., materials, funds, staff) to the activity."

Which varies ever so slightly from the proposed definition: "A partnership is a formal arrangement between the library and another organization that enables the two entities to support each other and work together towards shared goals."

From Dennis Nangle, Senior Program Officer, IMLS: We have this definition in place because many statewide projects coming out of a state library have a lot of collaborations, but not necessarily partners. For example, a statewide training in which staff from several library systems attend is not considered a partnership, but if the State Library worked with a local university, who agreed to provide their facilities to host the training, that would be considered a partnership. You’ll notice that our definition uses the term “formal” rather than “written” agreement. Most often these agreements are written, but our definition provides a little bit of flexibility in how those agreements are established/implemented.

**Comment by mgolrick** [comment]
While I understand the need for this data, is this really something that we want to add to the ANNUAL collection of data? Is it not something that would be better served by either a one-shot, or a periodic (every x-years) survey separate from the annual data collection.

I have a huge concern about the data gathering burden - not just for the small libraries, but for the larger libraries also. The numerous COVID questions were a stumbling block for some of my libraries - although I do support having asked them.

We need to pay close attention to the added burden. It is a simple Y/N set of questions, but with complex definitions. On first glance it will seem overwhelming to many, and may result in postponement of completion of the survey.

**Comment by jamiemott** [comment]
We in Idaho also have a concern about adding several new questions after the massive number of questions added last year. I think Michael's comment is correct that this does not need to be part of the annual survey.  A lot of libraries really limited services during this time and may have let some partnerships lapse due to COVID restrictions, etc.  I'm not sure we would start getting really great data on this question for some time due to the pandemic's lingering issues.

**Comment by kjcmetzger** [comment]
I am concerned that libraries would not understand what constitutes a "formal arrangement." Does this mean a signed contract? If not a signed contract, how would they know it is a formal arrangement? I also concur with the comment above that definitions should be consistent with those used in the State Program Report or in the SLAA survey.

**Comment by yanademireva** [comment]
I agree that a snapshot (2 years? 3 years?) is a better way to get at this important data, rather than an annual collection.

I would also add that the resulting data - partnerships by type of organization by state/region/type of library - isn't necessarily adding value, or generating data that libraries can then use when making decisions about their partnership initiatives, or when comparing themselves with peers. It's a given that libraries have partner organizations, and enumerating these partnerships isn't the data that I would want to see. Rather, qualitative narratives about those partnerships would be much more valuable with legislators and other stakeholders, and those would be a state/local level data collection that may not translate nationally.

In MD, we actually collect this data for Summer Reading programs (only), and ask that it be accompanied by qualitative pieces like stories and photographs. We do get valuable information on types of partnerships, because it's contextualized and supported by those stories; without them, we would just say that libraries have partners, and lots of them, but not what it is that we do with those partners.

I agree with the need to show the ways in which libraries serve communities. I just think that if we are looking to communicate externally to stakeholders about this work, this doesn't (to me at least) go very far in that direction. A more nuanced snapshot, with detailed questions, would go much further, I think, than just taking a quick pass on an annual basis.

**Comment by nguidryhall** [comment]
I strongly agree with those who question adding this group to the annual collection.  To put it simply, the value of the data that might be gathered on partnerships is not worth the effort and likely frustration on the part of our libraries.  In Florida, we are making a huge leap in the number of questions incorporated into next year’s survey, with the addition of this year’s IMLS program details and some of our own questions that were planned earlier. The volume of additional data points needs to be controlled rather than expanded. Perhaps dated questions that are no longer relevant should be sunset before or when new ones are added to the survey?

**Comment by timrohe** [comment]
I am against adding these questions on a recurring basis for many of the reasons raised above.  Primarily, the definitions are confusing (count this, not that) and I am concerned about the amount of questions we're adding to the survey every year.  Regarding the later concern, I am likely going to reach a point in NH where I have libraries just stop responding because it is too burdensome for them and I have no carrot or stick to make them.  It's easy for states that dole out state aid money to mandate that libraries respond, but some of us do not have that luxury.

**Comment by rfuquaSLO** [comment]
I just want to echo a +1 to @timrohe 's comment above about reporting burden on libraries. 
And no matter how fully-formed our definition and guidance for will be for what constitutes a "partnership,", I think in reality our libraries would make a wild range of interpretations, subsequently watering down this data point. 
Alternately, if there is a more immediate need for *some* level of data on library partnerships, a researcher could leverage the State Program Report data, filter it by public library grant recipients, and get a sense of what formal partnerships are being reported on LSTA (and soon CARES and ARPA)-funded projects.

**Comment by sgoek** [comment]
PLA had been considering adding a question like this to one of our new topical surveys, which means the question would be asked every 3 years. If this is added to the PLS, then we would most not likely include it on any PLA survey. The draft question included many of these same options for types of partners, but also a few more granular options:

- Colleges/universities
- Community colleges
- Daycares, Head Start centers, or preschools
- Healthcare providers or clinics
- K-12 school(s) or school district(s)
- Local businesses
- Local government agency
- Local nonprofits or community centers
- Museums, historical societies, or other cultural institutions
- Other library systems
- Parks and recreation
- Philanthropic foundations or organizations
- Prisons or juvenile detention centers
- Senior centers, residences, or retirement homes
- State government agency
- Tribal organization

**Comment by kjcmetzger** [comment]
I think that this set of questions fits better in the PLA topical surveys that @sgoek mentioned.
