### ISSUE TITLE
Addition - Overdue Fines

### ISSUE THREAD

**Issue by enielsen-air** [IMLS/public-libraries-survey#48]
**SUBMITTER:**
Evan Nielsen (AIR) on behalf of IMLS and the LSWG PLS Methods Ad Hoc Subcommittee

**NEW DATA ELEMENTS:** 
•	Current Overdue Fine Policy (data element 504)
•	Overdue Fine Revenue (data element 505)
•	Date of Overdue Fine Policy Change (data element 506)

**RATIONALE:**
This proposal adds three data elements related to a library’s overdue fine policy. Some public libraries have recently eliminated overdue fines as a way to improve equity in library services because they have determined that overdue fines disproportionately affect members of their communities who have few if any options for the kinds of services that the public library provides. The trend in curtailing overdue fines anecdotally appears to have accelerated during the COVID-19 pandemic. These proposed data elements would allow IMLS to report on the current status of this trend with comprehensive, national level data that is not currently available.

These proposed data elements are currently being vetted in one-hour interviews with ten respondents from public libraries of various sizes in seven different states. These interviews, along with feedback from SDCs via this forum, will inform the work of an ad hoc subcommittee of LSWG members and staff from IMLS and AIR to refine the proposed data element definitions and conduct another round of interviews in the fall. 

The three data elements presented in this proposal should be approved or rejected as a set.

**PROPOSED DEFINITIONS:**
See below or in attached file for the proposed definitions.
[PLS Overdue Fine Data Elements for FY22.docx](https://github.com/IMLS/public-libraries-survey/files/6928267/PLS.Overdue.Fine.Data.Elements.for.FY22.docx)

**Current Overdue Fine Policy (data element 504)**
As of the beginning of the reporting period, does the library charge overdue fines to users when they fail to return physical materials on or before the date due? 

NOTE: Overdue fines are monetary penalties that typically increase according to the number of days the materials are overdue. Overdue fines are not replacement costs for lost or damaged materials.

Select one of the following:
□ 	Yes, overdue fines are charged to all types of users and for all types of physical materials
□ 	Yes, but overdue fines are charged only to some types of users or only for some types of physical materials
□ 	No, overdue fines are not charged to any types of users or for any types of physical materials 

**Overdue Fine Revenue (data element 505)**
If the library charges overdue fines, report the total amount of overdue fines collected during the reporting period. Do not count replacement costs collected for lost or damaged materials. This amount is a subset of Other Operating Revenue (data element #303).
$___________
-1	Unknown
-3	Not Applicable [if data element 504=No]

**Date of Overdue Fine Policy Change (data element 506)**
If the library does not charge overdue fines, when was this policy enacted?
_ _ / _ _ _ _ [MM/YYYY]
-1	Unknown
-3	Not Applicable (e.g., if library has never charged overdue fines) [if data element 504=Yes]

**Comment by megdepriest** [comment]
I've spent the past five years or so working on the fine free movement, and what I've come to learn is that it is very common for libraries to drop fines on books, but not on DVDs, videos, hotspots, and other physical items. If we combine users and materials, the data will not be useful or demonstrate what's happening in the world of late fines.

Of libraries that have changed their late fines policies, there are those who have dropped for all users, but some materials. Or just children, and some materials.  Or just children and YA, but for all materials & for adults, just books.  I doubt there are many, **if any**, that dropped late fines for all users and all materials.   

Just like live and virtual programming, the number of questions grows. But you get a better picture of what's happening in libraries.

I think we have to separate users and materials:

Does your library charge a daily fine for late return of print materials? 
Does your library charge a daily fine for late return for other physical materials? (My guess will be most do: hotspots, laptops, Chromebooks, DVDs, records, etc.)

Does your library charge daily fines for late return of children's print materials?
Does your library charge daily fines for late return of young adult print materials?
Does your library charge fines for late return of adult print materials?

**Comment by mariabernier10601** [comment]
Ditto Meg's first two paragraphs, but I'm not keen on expanding the number of questions further. Also, many of my libraries are "99% fine-free," meaning they charge fines only for a few things like hotspots and museum passes, and they won't know how to answer question 506 as it's currently worded. It could be changed and simplified to "If the library does not charge overdue fines on books, when was this policy enacted?" Or, "when was the library's overdue fine policy last updated?"

**Comment by mgolrick** [comment]
Louisiana gathers information on two of the three items proposed. The fine revenue has been part of the detailed revenue portion of our survey for many years (longer than I have been doing it). I have attached our revenue questions - fines are lumped in with fees in the "Other Revenue" category.

I have not yet analyzed the fine free data - this was our first year. The questions we asked are:

1.21a. Is your library fine free? Please choose one of the options: 
	Yes
	No
	For some material types
	For some patrons
	Other (please specify)
1.21b. If you are fine free by material type (you may choose multiple options): 
	Children's materials
	Young adult materials
	All youth materials (children's and YA)
	Large print
	N/A
	Other (please specify)
1.21c. If you are fine free by borrower category, what groups? (you may choose multiple options):
	Children
	Young Adult
	Seniors (55+)
	Seniors (65+)
	N/A
	Other (please specify)

We did not ask for date of change, some of that information is included in the "Other" comments - of which there were many.
[Louisiana – Annual Report Questions-Instructions.docx](https://github.com/IMLS/public-libraries-survey/files/6975838/Louisiana.Annual.Report.Questions-Instructions.docx)

**Comment by yanademireva** [comment]
While I think this data would be great to have, I am also not too enthusiastic about the number of questions. One suggestion would be to use a matrix format, but not sure how feasible this would be with vendors? Regardless, I also am wondering if there isn't a better way to collect this rather than in the PLS - perhaps PLA topical surveys? Outside of the scope of this discussion, I know.

As another example, here in MD we recently had legislation pass making all juvenile (children's) materials fine free. Therefore, every library here would answer yes to the second option in 504, but what data would that get us? It lumps together libraries that are only fine-free for children, and those that are fine-free for all - this doesn't seem granular enough to be useful, though of course I'm sure I'm not thinking of every use case out there.

**Comment by kjcmetzger** [comment]
In RI, if a library charges a fine for the item, even if the fine is collected, it may not ever reach the owning library, if the transaction occurs at a different library. Also, the public library consortium (there is only 1 in RI, they are all members) recently approved a rule that the library completing the transaction can waive any fines. I feel any data collected from RI would be worthless.

**Comment by angelakfox** [comment]
I have concerns about adding multiple **recurring** questions on fines for something that seems unlikely to change much/any once a library makes the leap to fine free. I tend to fall with those voting for a one-off snapshot survey through other means. 

Indiana does occasionally collect the data, but we do it in a section of supplemental questions every few years. While it's not going to provide up-to-the-minute information about the exact number of libraries that are fine-free (or partially fine-free - something else that can complicate answering these sorts of questions), it's enough to have a rough idea of the number and the system-size breakdown, as well as to provide evidence that the movement's gaining traction.

**Comment by mgolrick** [comment]
Simply supporting @yanademireva and @angelakfox about the number of ONGOING questions.

Should there be a separate discussion about "flash surveys" or "one-shot" surveys? Or is this where we work more closely with PLA and PLDS to encourage them to do that kind of survey and "leave the census to us"?

**Comment by rfuquaSLO** [comment]
I share most of the concerns already voiced above, especially what @kjcmetzger describes with how fines are actually collected within consortium -- we would have the same issue here, but for 6 or 7 of our consortia. 

Additionally, I also have two bigger-picture concerns:

- A lot of libraries (municipal, especially) don't ever see the fine "revenue" they collect come back into the library coffers. In many cases, it just gets dumped into a more general pot of cash at the city level and there's no guarantee that they will be used to support library services. So.... is it still "library revenue" at that point?
- Also (with thanks to the fine-free movement), my colleagues and I here are actively trying to move libraries away from thinking about fine revenue as "revenue." I.e., we really want more libraries to get away from seeing overdue fines as something they can -- and should -- be using in their regular budgeting process. I realize this is a bit of a "pie-in-the-sky" perspective, but I think there's a lot to consider in how we're framing our language here.

We recently overhauled [our survey questions about fines](https://libguides.osl.state.or.us/c.php?g=1109992&p=8092110) (we've been collecting fine schedule data for years) to capture better data on the movement toward fine-free (see @megdepriest 's comment re: fines based on item type, because this *definitely* applies in Oregon). We now ask libraries to report fine *amounts* for the following. 901-903 are all incremental dropdowns, with a '$0.00 - we don't charge fines' option in each:

- 901 Daily overdue fine for adult materials.
- 902 Daily overdue fine for children's materials.
- 903 Daily overdue fine for other materials.
- 904 Notes on fines (optional question to describe "other materials" reported in 903; libraries also often report policy changes here, too)

FWIW, as @mgolrick mentioned, we still ask libraries to report fine- and fee-based "revenue" in the big "Other Revenue" catch-all categories, which would also include revenue from sources like foundations, private grants, endowments, etc. So there is zero granularity there to parse out fine "revenue."

**Comment by nguidryhall** [comment]
For this group, I will agree that the first proposed question is useful.  I had added a similar question to Florida’s next survey version.  I would prefer not to add the other two.  The last one especially has limited value.

**Comment by timrohe** [comment]
NH collected this data as a supplemental question a couple years back, but I do not support it being a recurring question on the PLS.  Honestly, I didn't find the data that useful.  Most libraries charge fines for **_some_** items, but knowing just that doesn't really tell you anything.  The next temptation would be to break it down further, like @mgolrick does in Louisiana, or adding a comments section about what you do and do not charge fines for, which I would absolutely not be in favor of doing at the national level on a recurring basis.

**Comment by klow-air** [comment]
Partially passed. ODFINE (As of the end of the reporting period, does the library charge overdue fines to any users when they fail to return physical print materials by the date due?) was added. Expects a Y/N response.
