### ISSUE TITLE
Addition - Number of registered users active in last year

### ISSUE THREAD

**Issue by enielsen-air** [IMLS/public-libraries-survey#59]
**Submitter:** 
Evan Nielsen, AIR

**Description of Change:**
Number of registered users (cardholders) that accessed services with the card during the reporting period (last 12 months). This would include circulating material as well as accessing electronic resources requiring user-level authentication. Could also split into three categories: (1) physical only, (2) electronic only, (3) both physical and electronic.

**Rationale:**
IMLS has historically not featured the existing "Registered Users" data element in analysis/reports because of caution from stakeholders that those figures may not be reliable (due to inconsistent record purging). Furthermore, differences in library card expiration policies mean those numbers aren't directly comparable. Rather than revise that existing data element, this proposal is to add a new data element (or three) to capture a consistent measure of the number of registered users that actually used library services (that require registration) in the past year. The data would allow IMLS to make more accurate statements about the proportion of the U.S. population that used a public library in the past year (again, not including services that don't require registration).

**Potential methodological issues:**
Libraries that don't have an ILS or other computerized user registration will likely not be able to report this number. 
Should non-resident users be included in this count?

**States already collecting:**
Virginia (according to Measures that Matter list from FY 2017)

**Comment by mariabernier10601** [comment]
I checked with a coworker who used to fill out our state report for his library system with five locations. He could have reported the number of active users of physical materials based on data from their particular ILS. However, he’s not convinced that every ILS used in our state is configured to capture the last checkout date and allow reporting on that field. 

Connecticut public libraries use 18 different ILSs, plus a couple of libraries have no ILS.

68% of reporting libraries belong to a consortium that could help them run a report to figure out the number of active users of physical materials. 

32% of reporting libraries are not part of a consortium, a few because their resources are very robust and the consortium wouldn’t benefit them, but most because they’re so small and under-resourced that they can’t afford it or see the need. Most of these libraries would need help counting active users of physical materials. I have no way to help them. 

Regarding circulating e-resources:
Many libraries provide more than one option for e-circ, including Overdrive, Hoopla, Kanopy, etc. In addition, the state library provides ebooks and e-audio through the Palace Project. The libraries would have to get the number of users from each vendor, who may or may not be able to provide this information. 

Regarding non-circulating e-resources such as databases that require library card numbers for access:
Probably the database vendors could provide a total number of unique users at each library based on library card prefix. 

How would libraries deduplicate patrons who may use a combination of services: physical materials from their library plus electronic resources from 1, 2, or more sources at their library or consortium plus electronic resources supplied by the state? Would we run the risk of duplicating or triplicating patrons? 

This proposal represents a heavy lift for our libraries. A guesstimate is that about two-thirds of CT libraries could eventually provide these counts, given enough time to prepare. The other third may never get there. Does that make this a more reliable data element than Registered Users, or less? Why don’t we try to fix the element that already exists, making it more specific procedurally, in order to make it more reliable?

**Comment by mgolrick** [comment]
Given the difficulty of getting some of my libraries to purge their records (or give counts) on a 3-year basis, going to annual will be a huge push. All the libraries in Louisiana are automated - that was a big push a while back. I think that if the definition is changed that the data will be even less reliable than the current data.

I ask the question "Year registration last purged" and as a result of those answers have footnotes in the report which I publish. (Some libraries have reciprocal arrangements, and/or offer cards to those employed in their community. Others just haven't purged their files - and seemingly won't.)

**Comment by enielsen-air** [comment]
@mariabernier10601 , thank you so much for this feedback. For physical circulation, I would think if we added such a data element to the PLS, the ILS developers would quickly get the message that they should create this report. It should be fairly easy to query this from the ILS database--but I fully agree that the burden to create that query should not fall on each individual library.

As for electronic circ, I had not considered that electronic material vendors' systems wouldn't leave a circulation record in the ILS. Would an ILS track each time a library card authenticates to an ILS? (This really gets into the weeds of what happens every time I use the Libby app on my phone.) It also makes me question how "integrated" an ILS really is if a library's electronic circulation is tracked entirely outside of one.

To avoid the need to de-dup the various electronic user counts, perhaps a solution could be to report the highest active user count for any of the electronic circulation platforms to which the library subscribes (understanding this would be an undercount of all electronic users). Then capture the physical users separately and NOT add them together. 

@mgolrick , I'm not sure if your comment was in reply to Maria's suggestion or my original post. But I just want to be clear that my suggestion was not to make the purging requirement to annual. I see the number of registered users and the number of those users that actually used the library in the past year as two distinct measures that serve different purposes.

**Comment by MFAroWI** [comment]
After discussion with our public library and electronic collections consultants, WI believes this addition would pose a significant burden to our libraries.  I understand per comments that intent was not to require an annual purge but I interpreted it that way when I first read the statement.  The proposed text needs clarification.   In addition, our electronic collections, BadgerLink in particular, produce an anonymous record of use without user-level information.

**Comment by yanademireva** [comment]
Operationalizing this would be an enormous lift that would, in my opinion, yield very little in the way of useful data. I'm not sure that we will be able to "make more accurate statements about the proportion of the U.S. population that used a public library in the past year (again, not including services that don't require registration)" precisely because registered borrowers doesn't really give a good idea of how the US population actually uses libraries. 

Regarding the proposed solutions for counting e-resource users - I would think we would want to sort out the existing e-resource issues? It is difficult enough to obtain reports from vendors on e-resource usage, and I wouldn't think that we want to tie yet another data element to this (very faulty) reporting.

**Comment by rfuquaSLO** [comment]
I also think this proposed change(s) would create a higher reporting burden for libraries without a good rate on return from the data. As much as I encourage our libraries to purge inactive patron records annually, it's considered a local-control issue here. Also, there are a number of ways to access electronic resources (databases, not e-books) in Oregon without going through a library card authentication process, so there is a lot of e-resource usage that we're unable to assign to individual libraries. Additionally, we have a significant population who are using other library services regularly (programs, reference services, space, etc.) but who choose not to get a card, so... <shrug>. 
I realize (#501) Library Visits is not a perfect metric either, but in my mind it would still be a better data point on library use in general.

**Comment by mariabernier10601** [comment]
There was some conversation a while back in the discussion forum about the difference between library card expiration dates (when the card becomes inactive and needs to be renewed) and purges, which I interpreted to be deletions of expired cardholder records from the ILS. There's usually a time period of months/years between an expiration date and when the record is actually purged from the system. 

So what if we clarified existing question 503 about number of registered borrowers to say that it should be the number of registered users as of the end of the reporting period, excluding any cards that expired more than a year prior? So tell me how many people have cards as of June 30, 2022, not including cards that expired on or before June 30, 2021. That should be an easy report to run in any ILS that has a field for expiration date.

**Comment by KristenCooke** [comment]
We currently ask for the number of Registered Users and we _did_ ask if they had purged their records in the last 5 years. It was a mixed bag. We eventually dropped the purged records subquestion since most of the libraries had such different systems for purging different records or card types. We ask for the number of registered users as of December 31 of the surveyed year. Like Ross notes, this is a local-control decision here. 

The biggest culprit in skewing this number were Borrowers who were not being purged from the ILS because they had outstanding fines over 100.00. Those accounts were rarely reactivated or resolved, so they stay year after year accumulating and inflating borrower records. We also have libraries statewide that offer family cards that tie multiple cards to one user account.
